<?php
/** Deterministic IPPanel contract coverage through the real production runtime. @package GravityNotify */
declare(strict_types=1);
namespace GravityNotify\Tests\Integration\RealRuntime;
use GFAPI;
use GFSMS\Integration\Dispatcher as LegacyDispatcher;
use GFSMS\Integration\Listener as LegacyListener;
use GravityNotify\Admin\Settings;
use GravityNotify\Delivery\AttemptStatus;
use GravityNotify\Delivery\Http\WordPressHttpTransport;
use GravityNotify\Delivery\Sms\IPPanelProvider;
use GravityNotify\Delivery\Sms\SmsCapability;
use GravityNotify\Delivery\Sms\SmsRequest;
use GravityNotify\GravityForms\FeedRuleSchema;
use GravityNotify\GravityForms\NotificationFeedAddOn;
use GravityNotify\Migration\CutoverRegistry;
use GravityNotify\Migration\CutoverSequence;
use GravityNotify\Migration\CutoverService;
use GravityNotify\Migration\LegacyRuntimeGuard;
use GravityNotify\Migration\ProductionRuntime;
use ReflectionClass;
use RuntimeException;
use WP_UnitTestCase;

final class IPPanelContractRealRuntimeTest extends WP_UnitTestCase {
	private const TOKEN='dummy-ippanel-token'; private const FROM='+989000000000'; private const TO='+989111111111'; private const MESSAGE='GNM deterministic simulator contract'; private const REFERENCE='424242';
	private int $form_id=0; private int $entry_id=0; private $settings_before; private $cutover_before;
	public function set_up(): void { parent::set_up(); $this->settings_before=get_option(Settings::OPTION,null); $this->cutover_before=get_option(CutoverRegistry::OPTION,null); delete_option(Settings::OPTION); delete_option(CutoverRegistry::OPTION); $this->remove_runtime_callbacks(); $this->reset_simulator(); }
	public function tear_down(): void { NotificationFeedAddOn::get_instance()->configure_processor(null); $this->remove_runtime_callbacks(); if(0<$this->entry_id){GFAPI::delete_entry($this->entry_id);} if(0<$this->form_id){NotificationFeedAddOn::get_instance()->delete_feeds($this->form_id);GFAPI::delete_form($this->form_id);} $this->restore_option(Settings::OPTION,$this->settings_before); $this->restore_option(CutoverRegistry::OPTION,$this->cutover_before); parent::tear_down(); }
	/** @testdox IPPANEL-CONTRACT-REAL-19 real GF/Flow production IPPanel path crosses loopback HTTP and reaches delivered */
	public function test_ippanel_contract_real_19_real_gf_flow_production_path_reaches_delivered(): void {
		self::assertSame('https://edge.ippanel.com/v1/api/send',$this->production_endpoint()); self::assertTrue(update_option(Settings::OPTION,array('ippanel_api_key'=>self::TOKEN,'sms_from_number'=>self::FROM,'bale_bot_token'=>''),false));
		$this->form_id=GFAPI::add_form(array('title'=>'GNM deterministic IPPanel contract','fields'=>array(array('id'=>1,'type'=>'text','label'=>'Marker')))); self::assertGreaterThan(0,$this->form_id);
		$feed=$this->add_target_feed(); $target=$this->add_target_step($feed); $source=$this->add_legacy_source_step(); $service=new CutoverService(); $scope=$service->prepare_flow('flow_step',$this->form_id,$source,$feed,$target); self::assertIsString($scope); self::assertSame(CutoverSequence::PREPARED,CutoverRegistry::record($scope)['state']); $this->register_legacy_and_guard_callbacks(); self::assertTrue($service->enable($scope)); self::assertTrue(CutoverRegistry::feed_authorized($feed)); $this->remove_legacy_sender_callbacks();
		$endpoint=$this->send_endpoint(); ProductionRuntime::register_with_test_ippanel_endpoint($endpoint); $urls=array(); $observer=static function($response,$context,$class,$args,$url) use (&$urls):void{unset($response,$class,$args);if('response'===$context&&is_string($url)){$urls[]=$url;}}; add_action('http_api_debug',$observer,10,5); try{$submission=GFAPI::submit_form($this->form_id,array('input_1'=>'simulator'));}finally{remove_action('http_api_debug',$observer,10);} self::assertNotWPError($submission); self::assertTrue((bool)rgar($submission,'is_valid')); $this->entry_id=(int)rgar($submission,'entry_id'); self::assertGreaterThan(0,$this->entry_id);
		$result=NotificationFeedAddOn::get_instance()->last_execution_result(); self::assertNotNull($result); self::assertCount(1,$result->attempts()); $attempt=$result->attempts()[0]; self::assertSame(AttemptStatus::SUCCESS,$attempt->status()); self::assertSame('ippanel',$attempt->provider_id()); self::assertSame(array(self::REFERENCE),$attempt->provider_references()); self::assertContains($endpoint,$urls); foreach($urls as $url){self::assertStringStartsWith('http://127.0.0.1:8765/',$url);self::assertStringNotContainsString('edge.ippanel.com',$url);} self::assertSame('delivered',$this->poll_delivery(self::REFERENCE,'delivered',1)); $state=$this->simulator_state(); self::assertSame(1,$state['send_count']??null); self::assertSame(1,$state['report_count']??null); printf('GNM_IPPANEL_CONTRACT_REAL_19=PASS socket=127.0.0.1:8765 provider=ippanel transport=wordpress send_count=1 report_count=1 message_status=2 external_provider_calls=0 real_sms=0'.PHP_EOL);
	}
	public function test_ippanel_simulator_rejects_invalid_contract_and_duplicate_send(): void { $e=$this->send_endpoint(); self::assertSame(401,$this->raw_status('POST',$e,array('Content-Type'=>'application/json'),$this->valid_body())); self::assertSame(401,$this->raw_status('POST',$e,array('Authorization'=>'wrong','Content-Type'=>'application/json'),$this->valid_body())); self::assertSame(405,$this->raw_status('GET',$e,array('Authorization'=>self::TOKEN))); self::assertSame(404,$this->raw_status('POST','http://127.0.0.1:8765/v1/api/wrong',array('Authorization'=>self::TOKEN,'Content-Type'=>'application/json'),$this->valid_body())); self::assertSame(415,$this->raw_status('POST',$e,array('Authorization'=>self::TOKEN,'Content-Type'=>'text/plain'),$this->valid_body())); self::assertSame(400,$this->raw_status('POST',$e,array('Authorization'=>self::TOKEN,'Content-Type'=>'application/json'),'{bad-json')); self::assertSame(422,$this->raw_status('POST',$e,array('Authorization'=>self::TOKEN,'Content-Type'=>'application/json'),'{}')); self::assertSame(200,$this->raw_status('POST',$e,array('Authorization'=>self::TOKEN,'Content-Type'=>'application/json'),$this->valid_body())); self::assertSame(409,$this->raw_status('POST',$e,array('Authorization'=>self::TOKEN,'Content-Type'=>'application/json'),$this->valid_body())); }
	public function test_ippanel_provider_parser_fails_closed_on_rejection_and_missing_reference(): void { $request=SmsRequest::plain(SmsCapability::PLAIN,array(self::TO),self::FROM,self::MESSAGE); foreach(array('provider_rejection'=>AttemptStatus::FAILED,'missing_reference'=>AttemptStatus::AMBIGUOUS) as $scenario=>$expected){$this->reset_simulator();$provider=new IPPanelProvider(self::TOKEN,new WordPressHttpTransport(),$this->send_endpoint().'?scenario='.$scenario);$result=$provider->send($request);self::assertSame($expected,$result->status());self::assertSame(array(),$result->provider_references());} }
	public function test_ippanel_delivery_report_fails_closed_for_terminal_and_bounded_pending(): void { self::assertSame('terminal_non_delivery',$this->poll_delivery(self::REFERENCE,'terminal_non_delivery',1)); self::assertSame('not_delivered',$this->poll_delivery(self::REFERENCE,'pending',2)); }
	private function production_endpoint(): string {$c=(new ReflectionClass(IPPanelProvider::class))->getReflectionConstant('ENDPOINT');if(false===$c){throw new RuntimeException('IPPanel production endpoint constant is unavailable.');}return(string)$c->getValue();}
	private function send_endpoint(): string {$v=getenv('GNM_IPPANEL_SIMULATOR_SEND_ENDPOINT');self::assertIsString($v);self::assertSame('http://127.0.0.1:8765/v1/api/send',$v);return$v;}
	private function report_endpoint(): string {$v=getenv('GNM_IPPANEL_SIMULATOR_REPORT_ENDPOINT');self::assertIsString($v);return$v;}
	private function reset_simulator(): void {$r=wp_remote_post('http://127.0.0.1:8765/_test/reset',array('headers'=>array('Authorization'=>self::TOKEN),'timeout'=>2));self::assertNotWPError($r);self::assertSame(200,wp_remote_retrieve_response_code($r));}
	private function simulator_state(): array {$r=wp_remote_get('http://127.0.0.1:8765/_test/state',array('headers'=>array('Authorization'=>self::TOKEN),'timeout'=>2));self::assertNotWPError($r);$d=json_decode(wp_remote_retrieve_body($r),true);self::assertIsArray($d);return$d;}
	private function valid_body(): string {return(string)wp_json_encode(array('sending_type'=>'webservice','from_number'=>self::FROM,'message'=>self::MESSAGE,'params'=>array('recipients'=>array(self::TO))));}
	private function raw_status(string $method,string $url,array $headers=array(),string $body=''):int{$r=wp_remote_request($url,array('method'=>$method,'headers'=>$headers,'body'=>$body,'timeout'=>2));self::assertNotWPError($r);return(int)wp_remote_retrieve_response_code($r);}
	private function poll_delivery(string $reference,string $scenario,int $max):string{for($i=1;$i<=$max;++$i){$url=add_query_arg(array('page'=>1,'per_page'=>10,'bulk_id'=>$reference,'scenario'=>$scenario),$this->report_endpoint());$r=wp_remote_get($url,array('headers'=>array('Authorization'=>self::TOKEN,'Content-Type'=>'application/json'),'timeout'=>2));if(is_wp_error($r)||200>wp_remote_retrieve_response_code($r)||300<=wp_remote_retrieve_response_code($r)){continue;}$d=json_decode(wp_remote_retrieve_body($r),true);if(!is_array($d)||true!==($d['meta']['status']??null)||!is_array($d['data']??null)){continue;}$record=reset($d['data']);if(!is_array($record)){continue;}$s=(string)($record['message_status']??'');if('2'===$s){return'delivered';}if(in_array($s,array('3','4'),true)){return'terminal_non_delivery';}}return'not_delivered';}
	private function add_target_feed():int{$id=GFAPI::add_feed($this->form_id,array('feedName'=>'Deterministic IPPanel target','message'=>self::MESSAGE,'recipient_source_type'=>FeedRuleSchema::RECIPIENT_FIXED,'recipient_source_value'=>self::TO,'channel'=>FeedRuleSchema::CHANNEL_SMS,'fallback_policy'=>FeedRuleSchema::FALLBACK_NONE),NotificationFeedAddOn::get_instance()->get_slug());self::assertNotWPError($id);self::assertIsInt($id);return$id;}
	private function add_target_step(int $feed):int{$id=(new \Gravity_Flow_API($this->form_id))->add_step(array('step_name'=>'Deterministic IPPanel target step','step_type'=>'gravity_notification_manager','feed_'.$feed=>'1'));self::assertGreaterThan(0,$id);return$id;}
	private function add_legacy_source_step():int{$id=(new \Gravity_Flow_API($this->form_id))->add_step(array('step_name'=>'Legacy source step','step_type'=>'approval'));self::assertGreaterThan(0,$id);return$id;}
	private function register_legacy_and_guard_callbacks():void{add_action('gravityflow_step_complete',array(LegacyListener::class,'on_step_complete'),10,5);add_action('gravityflow_step_complete',array(LegacyDispatcher::instance(),'handle_step_complete'),10,5);LegacyRuntimeGuard::boot();}
	private function remove_legacy_sender_callbacks():void{remove_action('gravityflow_step_complete',array(LegacyListener::class,'on_step_complete'),10);remove_action('gravityflow_step_complete',array('\\GFSMS\\Integration\\Listener','on_step_complete'),10);remove_action('gravityflow_step_complete',array(LegacyDispatcher::instance(),'handle_step_complete'),10);}
	private function remove_runtime_callbacks():void{$this->remove_legacy_sender_callbacks();remove_action('gravityflow_step_complete',array(LegacyRuntimeGuard::class,'begin_flow_step'),1);remove_action('gravityflow_step_complete',array(LegacyRuntimeGuard::class,'restore_flow_step'),11);remove_action('gravityflow_workflow_complete',array(LegacyRuntimeGuard::class,'begin_workflow'),1);remove_action('gravityflow_workflow_complete',array(LegacyRuntimeGuard::class,'restore_workflow'),11);remove_action('gform_after_submission',array(LegacyRuntimeGuard::class,'begin_direct'),1);remove_action('gform_after_submission',array(LegacyRuntimeGuard::class,'end_direct'),11);remove_filter('option_gfsms_settings',array(LegacyRuntimeGuard::class,'filter_direct_settings'),PHP_INT_MAX);remove_action('gfsms_process_payload',array(LegacyRuntimeGuard::class,'begin_process_payload'),1);remove_action('gfsms_process_payload',array(LegacyRuntimeGuard::class,'restore_process_payload'),11);remove_action('gfsms_retry_payload',array(LegacyRuntimeGuard::class,'begin_retry_payload'),1);remove_action('gfsms_retry_payload',array(LegacyRuntimeGuard::class,'restore_retry_payload'),11);}
	private function restore_option(string $name,$value):void{if(null===$value){delete_option($name);return;}update_option($name,$value,false);}
}
